[project]
name = "bdo-empire"
version = "0.8.0"
description = "Worker empire optimizer for BDO using HiGHS mip solver."
authors = [{ name = "Thell 'Bo' Fowler", email = "thell@tbfowler.net" }]

dependencies = [
    "bidict>=0.23.1",
    "certifi>=2026.6.17",
    "CTkToolTip>=0.8",
    "customtkinter>=6.0.0",
    "highspy>=1.15.0",
    "loguru>=0.7.3",
    "natsort>=8.4.0",
    "psutil>=7.2.2",
    "rustworkx>=0.18.0",
    "tabulate>=0.10.0",
    "urllib3>=2.7.0",
]

requires-python = ">=3.12"
readme = "README.md"
license = "Unlicense"

[project.scripts]
empire-optimizer = "bdo_empire.main:main"

[tool.uv]
package = true

[dependency-groups]
dev = ["twine>=6.1.0"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"bdo_empire" = ["data/**/*"]

[tool.ty.environment]
extra-paths = ["./src/bdo_empire"]
